### ISSUE TITLE
Opportunity to simplify the event handling

### ISSUE THREAD

**Issue by pmrcunha** [storycoding/rogue-online#12]
https://github.com/storycoding/rogue-online/blob/ee6913d0ede19a7b10bf1eb13497afa14644557a/src/stateful-components/app.jsx#L5

You can avoid this mapping by reading the `key` property, instead of the `keyCode`. This will give you a string like `ArrowDown`.

If you still need to map to the messages you defined for your socket, you can simply use an object, instead of the more verbose switch statement:

```js
const DIRECTIONS = {
ArrowUp: 'up',
ArrowDown: 'down',
ArrowLeft: 'left'.
ArrowRight: 'right',
};

// and then you can do 

keyPress({key}) {
      client.send(DIRECTIONS[key]);
  }
```

**Comment by storycoding** [comment]
fixed with [simplified input keys](https://github.com/storycoding/rogue-online/commit/ebaf6788e377cf1ef0410bb2545d1336793daaa6)
